<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [
	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
			
			,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"洗衣机管理",
                        "menuJump":"列表",
                        "tableName":"xiyiji"
                    }
                ],
                "menu":"洗衣机管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "修改",
                            "删除",
                        ],
                        "menu":"已预约洗衣机管理",
                        "menuJump":"列表",
                        "tableName":"yiyuyuexiyiji"
                    }
                ],
                "menu":"已预约洗衣机管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyanxinxi"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
							"新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }                    
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
							"预约",
						],
                        "menu":"洗衣机管理",
                        "menuJump":"列表",
                        "tableName":"xiyiji"
                    }
                ],
                "menu":"洗衣机管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "支付",
                            "删除",
                        ],
                        "menu":"已预约洗衣机管理",
                        "menuJump":"列表",
                        "tableName":"yiyuyuexiyiji"
                    }
                ],
                "menu":"已预约洗衣机管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "新增",
						],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyanxinxi"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }                    
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
